# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tGvFPHvXf4uAdlI_kJ5flRyuv9wLPxVk
"""

def hello_world(str):
  print(str)
  return str